$font = JetBrainsMono Nerd Font

# general
general {
    hide_cursor = true
}

# background
background {
    monitor =
    path = ~/.config/hypr/wallpapers/DSCF3581.JPG
    blur_passes = 2
}

# time
label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = $font
    position = -30, 0
    halign = right
    valign = top
}

# date
label {
    monitor =
    text = cmd[update:3600000] date +"%A, %d %B %Y"
    font_size = 30
    font_family = $font
    position = -30, -150
    halign = right
    valign = top
}

# greeting
label {
    monitor =
    text = Hi there, $USER
    color = rgb(c5c9c5)
    font_size = 30
    font_family = $font
    position = 0, 50
    halign = center
    valign = center
}

# input
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 0
    inner_color = rgb(c5c9c5)
    font_family = $font
    dots_size = 0.2
    dots_spacing = 0.2
    fade_on_empty = false
    fail_color = rgb(c4746e)
    position = 0, -35
    halign = center
    valign = center
}
