bind r source-file ~/.tmux.conf

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# start window numbering at 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# increase scrollback buffer size
set -g history-limit 10000

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# faster switching between next/prev window
bind -n C-p previous-window
bind -n C-n next-window

# helper script to switch sessions
bind -n C-s display-popup -E '~/.tmux/scripts/new-session.sh'

# resize panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z

set -g mouse on
set -g focus-events on

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

# plugins
set -g @plugin 'tmux-plugins/tpm'

# setup navigation between tmux and vim splits and panes 
set -g @plugin 'christoomey/vim-tmux-navigator'

# persist tmux sessions after computer restarts
set -g @plugin 'tmux-plugins/tmux-resurrect' 
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'

# automatically saves sessions every 15 minutes
set -g @plugin 'tmux-plugins/tmux-continuum' 
set -g @continuum-restore 'on'

# apply theme 
source-file ~/.tmux/kanagawa.conf

# initialize tmux plugin manager (this should be the last line of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
